import asyncio
from fastapi import APIRouter, HTTPException
from datetime import datetime, timezone
import uuid
from database import get_db
from models import Podcast, Subscription, Episode, Tag
from services import podcast_index, rss

router = APIRouter(prefix="/podcasts", tags=["podcasts"])


@router.get("/search")
async def search_podcasts(q: str, limit: int = 20) -> list[Podcast]:
    """Search podcasts via Podcast Index API."""
    results = await podcast_index.search_podcasts(q, limit)
    return [
        Podcast(
            id=str(r["id"]),
            title=r.get("title", ""),
            author=r.get("author", ""),
            description=r.get("description", ""),
            image_url=r.get("image"),
            feed_url=r.get("url", ""),
            website_url=r.get("link"),
            episode_count=r.get("episodeCount"),
        )
        for r in results
    ]


@router.get("/subscriptions")
async def list_subscriptions() -> list[Subscription]:
    db = await get_db()
    try:
        rows = await db.execute_fetchall("SELECT * FROM subscriptions ORDER BY subscribed_at DESC")
        # One query for every podcast's tags, rather than one per subscription.
        tag_rows = await db.execute_fetchall(
            """SELECT pt.podcast_id, t.id, t.name
               FROM podcast_tags pt JOIN tags t ON t.id = pt.tag_id
               ORDER BY t.name COLLATE NOCASE"""
        )
        by_podcast: dict[str, list[Tag]] = {}
        for r in tag_rows:
            by_podcast.setdefault(r["podcast_id"], []).append(Tag(id=r["id"], name=r["name"]))
        return [
            Subscription(**dict(r), tags=by_podcast.get(r["podcast_id"], []))
            for r in rows
        ]
    finally:
        await db.close()


@router.post("/subscriptions/{podcast_id}")
async def subscribe(podcast_id: str, feed_url: str, title: str, image_url: str = None):
    db = await get_db()
    try:
        await db.execute(
            """INSERT OR IGNORE INTO subscriptions
               (podcast_id, feed_url, title, image_url, subscribed_at, source)
               VALUES (?, ?, ?, ?, ?, 'podcast')""",
            (podcast_id, feed_url, title, image_url, datetime.now(timezone.utc).isoformat()),
        )
        await db.commit()
    finally:
        await db.close()
    return {"status": "subscribed"}


@router.delete("/subscriptions/{podcast_id}")
async def unsubscribe(podcast_id: str):
    db = await get_db()
    try:
        await db.execute("DELETE FROM subscriptions WHERE podcast_id = ?", (podcast_id,))
        await db.commit()
    finally:
        await db.close()
    return {"status": "unsubscribed"}


@router.get("/suggestions")
async def get_suggestions() -> list[dict]:
    """Return non-dismissed podcast suggestions generated by the daily job."""
    db = await get_db()
    try:
        rows = await db.execute_fetchall(
            "SELECT * FROM suggestions WHERE dismissed = 0 ORDER BY suggested_at DESC"
        )
        return [dict(r) for r in rows]
    finally:
        await db.close()


@router.post("/suggestions/{suggestion_id}/dismiss")
async def dismiss_suggestion(suggestion_id: str):
    db = await get_db()
    try:
        await db.execute("UPDATE suggestions SET dismissed = 1 WHERE id = ?", (suggestion_id,))
        await db.commit()
    finally:
        await db.close()
    return {"status": "dismissed"}


# Feed filters that map to a condition on the episode row.
_FEED_STATUS_SQL = {
    "transcribed": "e.transcript_status = 'done'",
    "distilled":   "EXISTS (SELECT 1 FROM gists g2 WHERE g2.episode_id = e.id)",
    "adfree":      "e.adfree_path IS NOT NULL",
    "downloaded":  "e.downloaded = 1",
}


# A refresh outlives the screen that started it. The work runs as a background
# task and its outcome is kept here, so navigating away and coming back can
# still show that one is running, or what the last one found. Single-user app,
# so module state is the right size for this — the same shape as the guards on
# transcription and channel imports.
_refresh: dict = {
    "running": False,
    "new": 0,
    "checked": 0,
    "failed": 0,
    "finished_at": None,
}


async def _refresh_all() -> None:
    """Check every subscription for new episodes. Never raises."""
    added = checked = failed = 0
    try:
        db = await get_db()
        try:
            # Same rule as the nightly job: a one-off video's channel is not a
            # subscription, so it is not polled.
            subs = await db.execute_fetchall(
                """SELECT podcast_id, feed_url, title FROM subscriptions
                   WHERE COALESCE(source, 'podcast') != 'youtube_video'"""
            )
        finally:
            await db.close()

        for sub in subs:
            podcast_id, feed_url = sub["podcast_id"], sub["feed_url"]
            checked += 1
            try:
                if podcast_id.startswith("yt-"):
                    from services import youtube_library
                    before = await _episode_count(podcast_id)
                    await youtube_library.sync_channel(
                        podcast_id[len("yt-"):], transcribe=False
                    )
                    added += max(0, await _episode_count(podcast_id) - before)
                else:
                    episodes = await rss.fetch_episodes(feed_url, podcast_id, limit=20)
                    added += await _insert_episodes(podcast_id, episodes)
            except Exception:
                # One dead feed must not stop the rest being checked.
                failed += 1
                continue
    finally:
        _refresh.update({
            "running": False,
            "new": added,
            "checked": checked,
            "failed": failed,
            "finished_at": datetime.now(timezone.utc).isoformat(),
        })


@router.post("/refresh")
async def refresh_subscriptions():
    """Start checking every subscription for new episodes.

    Returns immediately. The feed itself is a local query, so the refresh
    control used to re-read rows that could only change overnight — it looked
    instant because it did nothing. This actually goes out and asks, and
    because that takes seconds it runs in the background and is polled, so
    leaving the screen does not abandon it.

    Cheap on purpose: one RSS fetch per podcast, two requests per YouTube
    channel, and nothing transcribed or downloaded. The nightly job still owns
    that work.
    """
    if _refresh["running"]:
        return {"status": "already_running", **_refresh}
    _refresh.update({"running": True, "new": 0, "checked": 0, "failed": 0})
    asyncio.create_task(_refresh_all())
    return {"status": "started", **_refresh}


@router.get("/refresh/status")
async def refresh_status():
    """Whether a refresh is running, and what the last one found."""
    return {**_refresh}


async def _episode_count(podcast_id: str) -> int:
    db = await get_db()
    try:
        row = await db.execute_fetchone(
            "SELECT COUNT(*) AS n FROM episodes WHERE podcast_id = ?", (podcast_id,)
        )
        return row["n"] if row else 0
    finally:
        await db.close()


async def _insert_episodes(podcast_id: str, episodes: list) -> int:
    """Insert any episodes not already stored. Returns how many were new."""
    if not episodes:
        return 0
    db = await get_db()
    try:
        before = (await db.execute_fetchone(
            "SELECT COUNT(*) AS n FROM episodes WHERE podcast_id = ?", (podcast_id,)
        ))["n"]
        for ep in episodes:
            await db.execute(
                """INSERT OR IGNORE INTO episodes
                   (id, podcast_id, title, description, audio_url, duration_seconds,
                    published_at, image_url)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (ep.id, ep.podcast_id, ep.title, ep.description, ep.audio_url,
                 ep.duration_seconds,
                 ep.published_at.isoformat() if ep.published_at else None, ep.image_url),
            )
        await db.commit()
        after = (await db.execute_fetchone(
            "SELECT COUNT(*) AS n FROM episodes WHERE podcast_id = ?", (podcast_id,)
        ))["n"]
        return after - before
    finally:
        await db.close()


@router.get("/feed")
async def get_feed(
    q: str = "",
    tag_id: str = "",
    podcast_id: str = "",
    status: str = "",
    limit: int = 50,
) -> list[dict]:
    """Combined feed: episodes joined with subscriptions + distill counts.

    Optional filters, all combinable:
      q           substring of the episode or podcast title
      tag_id      only podcasts carrying this tag
      podcast_id  a single podcast
      status      one of _FEED_STATUS_SQL

    Filtering happens here rather than in the client because the feed is capped
    at `limit`: filtering a already-truncated page would silently hide matches
    that fall outside the most recent 50 episodes.
    """
    where: list[str] = []
    params: list = []

    if q.strip():
        # Title only. Descriptions are large HTML blobs (show notes, sponsor
        # links) and matching them buries real title hits in noise.
        like = f"%{q.strip()}%"
        where.append("(e.title LIKE ? OR s.title LIKE ?)")
        params += [like, like]

    if tag_id:
        where.append(
            "EXISTS (SELECT 1 FROM podcast_tags pt "
            "WHERE pt.podcast_id = e.podcast_id AND pt.tag_id = ?)"
        )
        params.append(tag_id)

    if podcast_id:
        where.append("e.podcast_id = ?")
        params.append(podcast_id)

    if status and status in _FEED_STATUS_SQL:
        where.append(_FEED_STATUS_SQL[status])

    clause = f"WHERE {' AND '.join(where)}" if where else ""
    params.append(max(1, min(limit, 200)))

    db = await get_db()
    try:
        rows = await db.execute_fetchall(
            f"""
            SELECT
                e.id, e.podcast_id, e.title, e.description, e.audio_url, e.duration_seconds,
                e.published_at, e.image_url, e.downloaded, e.transcript_status, e.ads_detected,
                s.title  AS podcast_title,
                s.image_url AS podcast_image,
                COUNT(g.id) AS distill_count
            FROM episodes e
            JOIN subscriptions s ON e.podcast_id = s.podcast_id
            LEFT JOIN gists g ON g.episode_id = e.id
            {clause}
            GROUP BY e.id
            ORDER BY e.published_at DESC
            LIMIT ?
            """,
            tuple(params),
        )
        return [dict(r) for r in rows]
    finally:
        await db.close()


@router.get("/{podcast_id}/episodes")
async def get_episodes(podcast_id: str, refresh: bool = False, limit: int = 100, offset: int = 0) -> list[Episode]:
    db = await get_db()
    try:
        if refresh:
            row = await db.execute_fetchone(
                "SELECT feed_url FROM subscriptions WHERE podcast_id = ?", (podcast_id,)
            )
            if not row:
                raise HTTPException(404, "Podcast not subscribed")

            # A YouTube channel has no RSS to parse — its stored feed_url is the
            # /videos tab, an HTML page. Refreshing one has to go through the
            # channel sync, or the button on its page silently does nothing.
            if podcast_id.startswith("yt-"):
                # Holds this connection open across the sync, which opens its
                # own. Safe in WAL mode, and it avoids closing a connection the
                # enclosing `finally` will close again if the sync raises.
                from services import youtube_library
                try:
                    await youtube_library.sync_channel(
                        podcast_id[len("yt-"):], transcribe=False
                    )
                except Exception as exc:
                    raise HTTPException(502, f"Could not refresh the channel: {exc}")
                # Asking a channel's own page for its latest videos is asking to
                # follow it. Promote a one-off row rather than filling it with
                # uploads while its badge still says nobody subscribed.
                await db.execute(
                    """UPDATE subscriptions SET source = 'youtube_channel'
                       WHERE podcast_id = ? AND COALESCE(source, '') = 'youtube_video'""",
                    (podcast_id,),
                )
                await db.commit()
                episodes = []
            else:
                episodes = await rss.fetch_episodes(row["feed_url"], podcast_id)
            for ep in episodes:
                await db.execute(
                    """INSERT OR IGNORE INTO episodes
                       (id, podcast_id, title, description, audio_url, duration_seconds, published_at, image_url)
                       VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                    (ep.id, ep.podcast_id, ep.title, ep.description, ep.audio_url,
                     ep.duration_seconds, ep.published_at.isoformat() if ep.published_at else None, ep.image_url),
                )
            await db.commit()

        # Bug 8: Paginate — cap at 500, default 100
        limit = min(max(limit, 1), 500)
        offset = max(offset, 0)
        rows = await db.execute_fetchall(
            "SELECT * FROM episodes WHERE podcast_id = ? ORDER BY published_at DESC LIMIT ? OFFSET ?",
            (podcast_id, limit, offset),
        )
        return [Episode(**dict(r)) for r in rows]
    finally:
        await db.close()
