"""
Unit tests for auto-snips (backend/services/auto_snipper.py).

The timestamps here are generated by a model, so the tests are mostly about
what happens when they are wrong: out of range, duplicated, or missing. A bad
timestamp must degrade the excerpt, never produce a seek into nothing.
"""
import json
from unittest.mock import patch

import pytest

from services import auto_snipper


def make_words(duration: int = 600, per_second: int = 2) -> list[dict]:
    """A synthetic transcript: `per_second` words for every second."""
    words = []
    step = 1 / per_second
    for i in range(duration * per_second):
        t = i * step
        words.append({"word": f" w{i}", "start": round(t, 2), "end": round(t + step, 2)})
    return words


WORDS_JSON = json.dumps(make_words())


def reply(snips):
    return {"snips": snips}


class TestPickSnips:

    def test_a_picked_moment_becomes_a_gist_shaped_row(self):
        with patch.object(auto_snipper.llm, "run_json",
                          return_value=reply([{"start_seconds": 120, "quote": "q", "insight": "i"}])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert len(out) == 1
        s = out[0]
        assert s["start_seconds"] == 120
        assert s["end_seconds"] > s["start_seconds"]
        assert s["text"]                                  # excerpt drawn from the transcript
        assert json.loads(s["summary"]) == {"quote": "q", "insight": "i"}

    def test_the_excerpt_comes_from_the_transcript_not_the_model(self):
        """The quote is the model's; the stored text has to be what was said."""
        with patch.object(auto_snipper.llm, "run_json",
                          return_value=reply([{"start_seconds": 100, "quote": "invented", "insight": "i"}])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert "invented" not in out[0]["text"]
        assert "w200" in out[0]["text"]                   # 100s * 2 words/s

    def test_a_timestamp_past_the_end_is_clamped_into_the_episode(self):
        with patch.object(auto_snipper.llm, "run_json",
                          return_value=reply([{"start_seconds": 99999, "quote": "q", "insight": "i"}])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert out and out[0]["start_seconds"] <= 600
        assert out[0]["text"]                             # still lands on real words

    def test_a_negative_timestamp_is_clamped(self):
        with patch.object(auto_snipper.llm, "run_json",
                          return_value=reply([{"start_seconds": -50, "quote": "q", "insight": "i"}])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert out and out[0]["start_seconds"] == 0.0

    def test_moments_seconds_apart_are_one_moment(self):
        """Two timestamps inside the same window describe the same passage."""
        with patch.object(auto_snipper.llm, "run_json", return_value=reply([
            {"start_seconds": 200, "quote": "a", "insight": "i"},
            {"start_seconds": 205, "quote": "b", "insight": "i"},
            {"start_seconds": 400, "quote": "c", "insight": "i"},
        ])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert [s["start_seconds"] for s in out] == [200, 400]

    def test_more_snips_than_asked_for_are_dropped(self):
        many = [{"start_seconds": i * 120, "quote": "q", "insight": "i"} for i in range(6)]
        with patch.object(auto_snipper.llm, "run_json", return_value=reply(many)):
            out = auto_snipper.pick_snips(WORDS_JSON, max_snips=2)
        assert len(out) == 2

    def test_an_unusable_timestamp_is_skipped_not_fatal(self):
        with patch.object(auto_snipper.llm, "run_json", return_value=reply([
            {"start_seconds": "not a number", "quote": "q", "insight": "i"},
            {"start_seconds": 300, "quote": "q", "insight": "i"},
        ])):
            out = auto_snipper.pick_snips(WORDS_JSON)
        assert [s["start_seconds"] for s in out] == [300]

    @pytest.mark.parametrize("bad", ["", "not json", "[]", json.dumps([])])
    def test_no_transcript_means_no_snips(self, bad):
        with patch.object(auto_snipper.llm, "run_json") as run:
            assert auto_snipper.pick_snips(bad) == []
        assert not run.called          # never spends a model call on nothing

    def test_a_failed_model_call_is_not_an_error(self):
        """A missing auto-snip costs the user nothing; a crashed sync costs a night."""
        with patch.object(auto_snipper.llm, "run_json", return_value=None):
            assert auto_snipper.pick_snips(WORDS_JSON) == []

    def test_a_reply_with_no_snips_is_respected(self):
        """'Nothing here stands on its own' is a valid answer."""
        with patch.object(auto_snipper.llm, "run_json", return_value=reply([])):
            assert auto_snipper.pick_snips(WORDS_JSON) == []


class TestBuildRows:

    def test_rows_are_flagged_as_automatic(self):
        snips = [{"start_seconds": 10.0, "end_seconds": 70.0, "text": "t", "summary": "{}"}]
        rows = auto_snipper.build_rows(snips, "ep1", "pod1", "Ep One", "Pod One")
        assert len(rows) == 1
        row = rows[0]
        assert row[1:5] == ("ep1", "pod1", "Ep One", "Pod One")
        assert row[-1] == 1                       # auto flag
        assert row[0] and row[0] != rows[0][1]    # its own uuid

    def test_each_row_gets_a_distinct_id(self):
        snips = [
            {"start_seconds": 10.0, "end_seconds": 70.0, "text": "a", "summary": "{}"},
            {"start_seconds": 90.0, "end_seconds": 150.0, "text": "b", "summary": "{}"},
        ]
        rows = auto_snipper.build_rows(snips, "ep1", "pod1", "Ep", "Pod")
        assert rows[0][0] != rows[1][0]
